name: Python BE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, linux, ARM]

    steps:
      - uses: actions/checkout@v2
        with:
          clean: false
      - name: Run initial setup
        run: sudo python3 initial_setup.py -y
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
